// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSNkGtoFCl1eTnojcDT4pXSE95aSFnf4g',
    appId: '1:524060994609:web:ddcbc085c992fa1bbff910',
    messagingSenderId: '524060994609',
    projectId: 'jack-cops-and-rubbers-dev',
    authDomain: 'jack-cops-and-rubbers-dev.firebaseapp.com',
    storageBucket: 'jack-cops-and-rubbers-dev.appspot.com',
    measurementId: 'G-RJYRCXR0QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQAW-jr0MQUsjGHNLrq69-ISAuZgYn98',
    appId: '1:524060994609:android:864193f069088546bff910',
    messagingSenderId: '524060994609',
    projectId: 'jack-cops-and-rubbers-dev',
    storageBucket: 'jack-cops-and-rubbers-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmgWUAqN9-TWe2gdgg2uAxGh-9dvoUQaI',
    appId: '1:524060994609:ios:3ef771dfeadc7acfbff910',
    messagingSenderId: '524060994609',
    projectId: 'jack-cops-and-rubbers-dev',
    storageBucket: 'jack-cops-and-rubbers-dev.appspot.com',
    iosBundleId: 'com.sawapy0630h12.copsAndRobbersClient',
  );
}
